server:
  port: 8080

# Database configuration
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/short_url?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: update
        show-sql: true


# Output logs to the console
logging:
  level:
    com.example.shorturl: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{15}) - %msg%n"


